os: osx
language: shell
addons:
  homebrew:
    packages: python3
before_install:
  - pip3 install virtualenv
  - virtualenv -p python3 ~/venv
  - source ~/venv/bin/activate
  - pip3 install poetry

install: poetry install
script: python -m touchbar_lyric
notifications:
  email:
    on_failure: never

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry build

deploy:
  provider: script
  script: poetry publish
  cleanup: false
  on:
    tags: true
    branch:
      - "master"
      - "/v?(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
